### ISSUE TITLE
ROIs vs. background

### ISSUE THREAD

**Issue by irenatfh** [cfperez/smbanalyze#10]
When the ROI and background are of different sizes, FRET calculation doesn't happen properly.

**Comment by ghost** [comment]
Do you mean frames?  What do you mean by different sizes?

**Comment by irenatfh** [comment]
As in, dimensions of one frame of each are different.  I showed Christian, and I think he knows what needs to be fixed.

**Comment by irenatfh** [comment]
Disregard the closing and reopening of the issue...figuring out how to use this thing.

**Comment by cfperez** [comment]
Hahaha :)

The software now throws an error to warn you that the ROI is out of bounds. Often it is a problem with 'relative' versus 'absolute' coordinates. If you are doing an ROI by eye with respect to bottom of the image, it is a 'relative' ROI. The VI on hasselhoff records ROIs with respect to the CCD, hence 'absolute'.

Add origin='relative' as the very first line in an roi file if you are making one by hand.
